### ISSUE TITLE
Using in Redis

### ISSUE THREAD

**Issue by ProninIgorr** [alevinval/fingerprints#1]
Hello. Have a question about ur code.  How and in what form is it better to store point data in Redis?
What is an example of a goclient that quickly compares prints stored (marshalled, etc., etc.) in radish with a sample, in priority - the option of participation - splitting into clusters, so that each client, by its id, receives only its own cluster for  jobs and get them from go (goroutines...) as quickly as possible.

**Comment by alevinval** [comment]
Have you validated first that this tool solves your problem? This is a pet project and I had intention to use a real fingerprint scanner to further improve it and actually use it with my finger, but I kinda dropped interest once I realised the fingerprint scanner I bought only supported windows. I'd be surprised this is actually ready to be used in production, but might give you a good start.

This is just a library, so it's up to you to choose whatever storage is more suitable for you, and what data-structure you want to use to keep the points. You just need to reconstruct the list of minutae in order to match two fingerprints, a list of minutiae, which only contains (x,y) coordinates + angle + enum for the type of minutiae. Simplest thing is marshal to JSON, if you want something fancier you might as well create your own protobuf in redis, and translate between that and the structure needed for the library. Seems an overkill if you are just playing with it.

Anyway, you are talking about jobs and some sort of pub-sub, to be honest I cannot really help you without any context, but even if I had it, this escapes the boundaries of this library and enters the boundaries of your own business application or whatever you are building.

**Comment by ProninIgorr** [comment]
yes, it works.  The only question remained in what format to put the output structure in the redish
